#!/usr/bin/env bash

# Check if the script is provided with the required number of arguments
if [ "$#" -ne 4 ]
then
    echo "Usage: $0 PATH_TO_FILE IP USERNAME PATH_TO_SSH_KEY"
else
    # Assign arguments to variables
    PATH_TO_FILE="$1"
    IP="$2"
    USERNAME="$3"
    SSH_KEY="$4"
    # Use scp to transfer the file to the user's home directory on the server
    # Disable strict host key checking with "-o StrictHostKeyChecking=no"
    scp -o StrictHostKeyChecking=no -i "$SSH_KEY" "$PATH_TO_FILE" "$USERNAME@$IP:~/"
fi

