#!/usr/bin/env bash
sudo apt-get -y update
sudo apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
echo "Hello World!" > /etc/nginx/html/index.html
echo "server {
    listen 80;
    server_name localhost;

    location / {
        echo 'Hello World!';
    }
}" > /etc/nginx/sites-available/default
sudo nginx -s reload
