#!/usr/bin/env bash
sudo apt-get update
sudo apt-get install -y nginx
mkdir /etc/nginx/html
touch /etc/nginx/html/index.html
sudo echo "Hello World!" > /etc/nginx/html/index.html
printf %s "server {
     listen      80 default_server;
     listen      [::]:80 default_server;
     root        /etc/nginx/html;
     index       index.html index.htm;
}
" > /etc/nginx/sites-available/default
sudo nginx -s reload
