#!/usr/bin/env bash
# This script displays 'Best School' 10 times using while loop
i=1
while [ $i -le 10 ]
do
    if [ $i -ne 9 ]
    then
	echo 'Best School'
    else
	echo 'Best School'
	echo 'Hi'
    fi	
    i=$((i + 1))
done
