#!/usr/bin/env bash
# This script displays 'Best School' 10 times using while loop
hour=0
while [ $hour -le 12 ]
do
    echo Hour: $hour
    hour=$((hour + 1))
    min=1
    while [ $min -le 59 ]
    do
	echo $min
	min=$((min + 1))
    done
done
