#!/usr/bin/env bash
# displays information about the School file

name="School"

if [ -e $name ]
then
    echo "School file exists"
    if [ -s $name ]
    then
	echo "School file is not empty"
    else
	echo "School file is empty"
    fi
    if [ -f $name ]
    then
	echo "School is a regular file"
    fi
else
    echo "School file does not exist"
fi
