#!/usr/bin/env bash

# Name of the private key file
private_key_file="school"

# Number of bits in the key
key_bits="4096"

# Passphrase to protect the key
passphrase="betty"

# Create the RSA key pair with the specified settings
ssh-keygen -t rsa -b "$key_bits" -f "$private_key_file" -N "$passphrase"
